### ISSUE TITLE
Wrong dependency info in README

### ISSUE THREAD

**Issue by stefanzilske** [StephenOTT/camunda-prometheus-process-engine-plugin#21]
Hey @StephenOTT 

I just wanted to upgrade my SpringBoot example to your latest version and could not make it work using the dependency to jitpack you mention in the README.

Instead, it works using

```
	<dependency>
	    <groupId>com.github.StephenOTT</groupId>
	    <artifactId>camunda-prometheus-process-engine-plugin</artifactId>
	    <version>v1.6.0</version>
	</dependency>
```

Maybe you want to update the README?

Cheers,
Stefan

**Comment by StephenOTT** [comment]
🤦‍♂️ yes typo.  fixed 
https://github.com/StephenOTT/camunda-prometheus-process-engine-plugin/commit/8ae84958b8f638665189e443351de14117679801
